### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'miniters'

### ISSUE THREAD

**Issue by SUP3RIA** [tqdm/tqdm#404]
I know that concurrency or multi-threading is not supported officially yet, but nonetheless I would like to see a fix for that.

I am using tqdm with Gevent in 50 "Greenlets" at the same time and it works just fine except I get this error.

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 109, in run
    if instance.miniters > 1 and \
AttributeError: 'tqdm' object has no attribute 'miniters'`

**Comment by RogerLiNing** [comment]
this works for me
```python
gevent.monkey.patch_all(thread=False)
```

**Comment by laserson** [comment]
I get the exact same error message when I have a `trange` nested in a `tqdm`.  It seems to happen when the inner loop is very fast, though I haven't verified this.  It doesn't seem to cause a problem though, just aesthetically worse.   Any way to fix it?

**Comment by harlowja** [comment]
I've also seen this:

Stack trace:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/jxharlow/.venv/lib/python2.7/site-packages/tqdm/_tqdm.py", line 147, in run
    if instance.miniters > 1 and \
AttributeError: 'tqdm' object has no attribute 'miniters'
```

**Comment by chengs** [comment]
Me too, I've also seen this.

**Comment by kkroening** [comment]
It's a race condition. Notice how a `TMonitor` is created in `tqdm.__new__` _before_ the instance is initialized. This chunk of code probably just needs to be moved from `tqdm.__new__` to `tqdm.__init__`:
```
        with cls._lock:
            cls._instances.add(instance)
```
That way the monitor doesn't try to look at instances until they've been initialized.

**Comment by kkroening** [comment]
It seems to happen more often with `gevent` for whatever reason. Using `gevent.monkey.patch_all(thread=False)` makes it less likely to happen, but probably still possible.

Another solution is to disable the monitor before creating a tqdm instance:
```
from tqdm import tqdm
tqdm.monitor_interval = 0
```

**Comment by casperdcl** [comment]
probably related to #383 and https://github.com/tqdm/tqdm/labels/synchronisation. Perhaps #493 means this is now fixed?

**Comment by casperdcl** [comment]
related: https://github.com/tqdm/tqdm/issues/323#issuecomment-267660789

**Comment by casperdcl** [comment]
`tqdm>=4.19.7` (thanks to #493) should have closed this. Happy to reopen if this is still an issue

**Comment by s-sajid-ali** [comment]
I'm still getting this error : 

```
4%|3         | 351/10000 [17:31<8:01:35,  2.99s/it]Traceback (most recent call last):
  File "exit_to_focus_direct.py", line 51, in <module>
    prop2d_cython_2_loop.exact_prop_2D_cython(in_wave,out_wave,L_in,L_out,0,0,wavel,z,250)
  File "prop2d_cython_2_loop.pyx", line 94, in prop2d_cython_2_loop.exact_prop_2D_cython
  File "/home/sajid/.conda/envs/intelpy3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 936, in __iter__
    if n - last_print_n >= self.miniters:
AttributeError: 'tqdm' object has no attribute 'miniters'

```
This is on Intel Xeon Phi with 250 threads. The error persists even after upgrading to tqdm=4.24.0
