### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by utkonos** [tqdm/tqdm#481]
`tqdm` is throwing a set changed size during iteration exception intermittently:
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vagrant/regex/lib/python3.6/site-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/lib/python3.6/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by utkonos** [comment]
version 4.19.4 on python 3.6.3

**Comment by casperdcl** [comment]
Sounds like disabled locks or non-functioning threading. Are you using windows?

You could disable the monitor thread by doing

```python
from tqdm import tqdm
tqdm.monitor_interval = 0
```

before the rest of your code

**Comment by solomatov** [comment]
I have the same issue on OSX

**Comment by utkonos** [comment]
I am on macOS as well.

**Comment by drnextgis** [comment]
Faced with the same issue in Ubuntu (tqdm==4.19.4, Python 2.7.12). Workaround by setting `monitor_interval` works.

**Comment by utkonos** [comment]
I'm still having this same exception occur with the current version, 4.19.5.

I also can confirm that `tqdm.monitor_interval = 0` is a valid workaround.

**Comment by wilrich-msft** [comment]
I have the same issue on Win10 / 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]:
```
from sklearn.cross_validation import KFold
scores = []
N_FOLDS = 10
from sklearn.utils import shuffle
X, Y = shuffle(X, Y, random_state=0)
cv = KFold(n=len(X), n_folds=N_FOLDS)

for train, test in tqdm(cv, total=N_FOLDS):    
    clf = neighbors.KNeighborsClassifier()
    clf.fit(X[train], Y[train])
    scores.append(clf.score(X[test], Y[test]))
```
resulting in
```
Exception in thread Thread-33:
Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\tqdm\_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by MattKleinsmith** [comment]
I received this error after switching to starmap from map, from the multiprocessing package. I went back to map and the error went away.

**Starmap code:**
```
from multiprocessing import Pool

def get_and_save_patch(out_path, img, i):
    img = random_crop(img, PATCH_SIZE)
    out_path_png = out_path.split('.')[0] + "_" + str(i) + "_.png"
    cv2.imwrite(out_path_png, img)

cameras = sorted(os.listdir(TRN_DIR))
for camera in tqdm_notebook(cameras):
    in_dir = osp.join(TRN_DIR, camera)
    out_dir = osp.join(TRN_64_DIR, camera)
    os.makedirs(out_dir)
    in_filenames = sort_files_by_int(os.listdir(in_dir))
    for in_filename in tqdm_notebook(in_filenames):
        in_path = osp.join(in_dir, in_filename)
        out_path = osp.join(out_dir, in_filename)
        img = np.array(cv2.imread(in_path))
        args = [(out_path, img, i) for i in range(NUM_PATCHES_PER_IMG)]  # Shallow copies.
        with Pool(NPROC) as pool:  # Multiprocessing.
            pool.starmap(get_and_save_patch, args)
```

**Map code:**

```
from multiprocessing import Pool

def get_and_save_patch(args):  ######### Diff.
    out_path, img, i = args  ######### Diff.
    img = random_crop(img, PATCH_SIZE)
    out_path_png = out_path.split('.')[0] + "_" + str(i) + "_.png"
    cv2.imwrite(out_path_png, img)

cameras = sorted(os.listdir(TRN_DIR))
for camera in tqdm_notebook(cameras):
    in_dir = osp.join(TRN_DIR, camera)
    out_dir = osp.join(TRN_64_DIR, camera)
    os.makedirs(out_dir)
    in_filenames = sort_files_by_int(os.listdir(in_dir))
    for in_filename in tqdm_notebook(in_filenames):
        in_path = osp.join(in_dir, in_filename)
        out_path = osp.join(out_dir, in_filename)
        img = np.array(cv2.imread(in_path))
        args = [(out_path, img, i) for i in range(NUM_PATCHES_PER_IMG)]  # Shallow copies.
        with Pool(NPROC) as pool:  # Multiprocessing.
            pool.map(get_and_save_patch, args)  ######### Diff.
```

**Comment by utkonos** [comment]
Without digging even deeper, I think the comment 'Shallow copies.' is telling. I have encountered exceptions just like this if I iterate on a shallow copy of an interable and operate on that same iterable inside the loop using del or pop or such operations. I bet that somewhere in there is `copy.copy()` rather than `copy.deepcopy()`. However, this is just a guess.

**Comment by utkonos** [comment]
Also, unfortunately, the workaround found above does not work 100% of the time. I am still encountering this bug even with the workaround `tqdm.monitor_interval = 0` in place.

**Comment by wjaskowski** [comment]
I get it on python 3.6.4 and tqdm 4.11.2 on Ubuntu 16.04.

**Comment by utkonos** [comment]
This is still happening for me on tqdm (4.19.8) on macOS using jupyter notebook.

**Comment by habibutsu** [comment]
I am found old fix, but which is absent in current code
https://github.com/tqdm/tqdm/commit/64f5e73024b48f88703a309da020b786631813d6

**Comment by casperdcl** [comment]
that was a hack before we introduced locks, which should have eliminated the problem. It would be nice to figure out and tackle the issue rather than reintroducing the hack

**Comment by habibutsu** [comment]
@casperdcl I think this is bad approach. This sounds for me like that you suggest do not resuscitate a patient until understand what is reason of incident or don't save the somebody from fire until not understand of fire reason.

A am agree that needed to figure out how to fix this correctly, but in the same time until this is not clear would be nice to make this hack.

**Comment by casperdcl** [comment]
xD not sure whether the analogy transfers, but re-added this all the same in `devel`

**Comment by casperdcl** [comment]
@javadnoorb if you upgrade to v4.20.0, do you still get this?

**Comment by javadnoorb** [comment]
@casperdcl I'm not sure. I can't get the upgrade with conda. But the error is not easily reproducible. I'm not getting it again with v4.19.9

**Comment by casperdcl** [comment]
v4.20.0 should be available: https://anaconda.org/conda-forge/tqdm

**Comment by javadnoorb** [comment]
I see. It's on conda-forge. It tries to downgrade python when I use that channel:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.1.18          |           py36_0         143 KB  conda-forge
    tqdm-4.20.0                |             py_0          34 KB  conda-forge
    python-3.6.4               |       hc3d631a_3        29.1 MB
    cryptography-2.2.1         |           py36_0         846 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        30.1 MB

The following packages will be UPDATED:

    certifi:         2018.1.18-py36_0     --> 2018.1.18-py36_0 conda-forge
    tqdm:            4.19.9-py36_0        --> 4.20.0-py_0      conda-forge

The following packages will be DOWNGRADED:

    ca-certificates: 2018.03.07-0         --> 2018.1.18-0      conda-forge
    conda:           4.5.0-py36_0         --> 4.3.34-py36_0    conda-forge
    cryptography:    2.2.2-py36h14c3975_0 --> 2.2.1-py36_0     conda-forge
    openssl:         1.0.2o-h20670df_0    --> 1.0.2n-0         conda-forge
    python:          3.6.5-hc3d631a_0     --> 3.6.4-hc3d631a_3   
```

**Comment by javadnoorb** [comment]
Thanks. I upgraded. Will post here if I encounter the error again.

**Comment by pymonger** [comment]
I still get the error with 4.21.0 on CentOS7 and python2.7.

**Comment by casperdcl** [comment]
@pymonger can you provide a trace of the error like in the original description?

**Comment by Borda** [comment]
I still see this error on Linux/Debian for various versions of python and also on Travis, Shippable or CircleCI
```
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/lib/python2.7/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by casperdcl** [comment]
This should only be a `TqdmSynchronisationWarning` rather than a `RuntimeError` in `tqdm>=4.21.0`. @pymonger regarding https://github.com/sdskit/sdscli/commit/1da033dc188d0cadbadf9bf55f4260fb28f0a36f you should catch the warning instead (`warnings.filterwarnings("ignore", category=tqdm.TqdmSynchronisationWarning)`)

**Comment by chengs** [comment]
@Borda eh, since tqdm>4.20.0, this ``RuntimeError: Set changed size during iteration`` warning should be replaced by a ``TqdmSynchronisationWarning``. So, please check if you are using the latest version of tqdm

**Comment by Borda** [comment]
Hello, I am not sure if it is connected, but now I see something like this"
`Exception KeyError: KeyError(<weakref at 0x7fbca8430050; to 'tqdm' at 0x7fbca83cb850>,) in <object repr() failed> ignored`

**Comment by casperdcl** [comment]
That looks like problems with deleting bars - a MWE would help

**Comment by Borda** [comment]
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
[xcb] Unknown sequence number while processing queue
      after 401 requests (401 known processed) with 2 events remaining.
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Exception KeyError: KeyError(<weakref at 0x7fdff8d6cba8; to 'tqdm' at 0x7fe01e71c710>,) in <object repr() failed> ignored
```

**Comment by chengs** [comment]
@Borda could you provide some code reproducing this error?

**Comment by Borda** [comment]
@chengs it is while running some scripts from [ImSegm](https://github.com/Borda/pyImSegm) so it is far to send just a piece of code...

**Comment by tinamorale** [comment]
The latest version of `tqdm 4.23.3` has a warning `TqdmSynchronisationWarning`. This makes my download fail. Downgraded the tqdm version to `4.19.7` which works.
OS: Mac
Python version: 3.6.5

**Comment by casperdcl** [comment]
`Warnings` should not cause failures. They print information. The correct way to suppress this is:

```python
from tqdm import tqdm, TqdmSynchronisationWarning
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore", TqdmSynchronisationWarning)
    # some code here...
```

RTM:
https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings
https://docs.python.org/3.6/library/warnings.html#temporarily-suppressing-warnings

This issue is patched in `tqdm>=4.20.0`, where the `Error` is replaced with a `Warning`.

**Comment by dhoomakethu** [comment]
So I was encountering random `RuntimeError: Set changed size during iteration` with tqdm `4.19.5` and came here to find a solution, I upgraded to latest (`4.23.4`) and now I get another error `Exception KeyError: KeyError(<weakref at 0x7f47a5664cb0; to 'tqdm' at 0x7f47a60be9d0>,) in <bound method tqdm.__del__`.

Basically , I am trying to download a bunch of files in loop , the download of the first file is succesfull but when starting to download the next file this error is thrown (note the download still continues ).

Here is my code snippet:
```
def download_file(snap, target_dir, url):
    local_filename = os.path.join(target_dir, snap)
    r = requests.get(url, stream=True, verify=False)
    if r.status_code != 200:
        log.error("Unable to download - {}: Error - {}".format(snap, r.json()))
        return
    size = int(r.headers.get('content-length'))
    chunk_size = 1024
    bars = int(size / chunk_size)
    with open(local_filename, 'wb') as f:
        if not size:
            f.write(r.content)
        else:
            size = float(size)
            for data in tqdm(r.iter_content(chunk_size),
                             desc="{}: ".format(local_filename),
                             total=bars,
                             bar_format="'{l_bar}{bar} [{rate_fmt}]",
                             unit='KB',
                             unit_scale=True, leave=False):
                f.write(data)

    return local_filename

for snap in snaps:
    download_file(snap, target_dir, url)
```

**Comment by BearTian** [comment]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Proj\antwork\code\antwork_backend\server\data_handlers\order\playback_hd.py", line 147, in run
    send_to_ws(channel=self.room_name, data=json.loads(msg))
  File "D:\Proj\antwork\code\antwork_backend\server\data_exchange.py", line 26, in send_to_ws
    asyncio.run(channel_layer.group_send(channel, send_data))
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 46, in run
    _cancel_all_tasks(loop)
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 54, in _cancel_all_tasks
    to_cancel = tasks.all_tasks(loop)
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 38, in all_tasks
    return {t for t in _all_tasks
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 38, in <setcomp>
    return {t for t in _all_tasks
  File "C:\Users\max\AppData\Local\Programs\Python\Python37\lib\_weakrefset.py", line 61, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration

**Comment by casperdcl** [comment]
should be fixed now (`tqdm>=4.32.2`)

closed by #700 & #754

**Comment by mondeja** [comment]
I'm getting [the same error](https://github.com/Zulko/moviepy/pull/1459/checks?check_run_id=1716666180#step:6:204) in Python3.6 with [tqdm v4.56.0](https://github.com/Zulko/moviepy/pull/1459/checks?check_run_id=1716666180#step:5:146). This does not happen in Python 3.7, 3.8 neither 3.9.

**Comment by schulzalbrecht** [comment]
> 
> 
> should be fixed now (`tqdm>=4.32.2`)
> 
> closed by #700 & #754

no, this isn't fixed. I've got this problem now.

**Comment by schulzalbrecht** [comment]
is there any proper solution to this problem instead of this workaround?

**Comment by Dobatymo** [comment]
I am still getting the error with 4.61.1 on windows.
The problem only occurs sometimes and is related to tqdm being called from different threads.

**Comment by casperdcl** [comment]
@Dobatymo can you post a traceback?

**Comment by Dobatymo** [comment]
I forgot which tqdm version caused this specific traceback, but it's a recent one and I think the traceback was the same for the latest version too.

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\site-packages\tqdm\_monitor.py", line 78, in run
    instances = self.get_instances()
  File "C:\Program Files\Python37\lib\site-packages\tqdm\_monitor.py", line 58, in get_instances
    return [i for i in self.tqdm_cls._instances.copy()
  File "C:\Program Files\Python37\lib\_weakrefset.py", line 92, in copy
    return self.__class__(self)
  File "C:\Program Files\Python37\lib\_weakrefset.py", line 50, in __init__
    self.update(data)
  File "C:\Program Files\Python37\lib\_weakrefset.py", line 119, in update
    for element in other:
  File "C:\Program Files\Python37\lib\_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by vTuanpham** [comment]
Still the same error
```
5879.1s	371	Traceback (most recent call last):
5879.1s	372	  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
5879.1s	373	    self.run()
5879.1s	374	  File "/opt/conda/lib/python3.10/site-packages/tqdm/_monitor.py", line 69, in run
5879.1s	375	    instances = self.get_instances()
5879.1s	376	  File "/opt/conda/lib/python3.10/site-packages/tqdm/_monitor.py", line 49, in get_instances
5879.1s	377	    return [i for i in self.tqdm_cls._instances.copy()
5879.1s	378	  File "/opt/conda/lib/python3.10/_weakrefset.py", line 97, in copy
5879.1s	379	    return self.__class__(self)
5879.1s	380	  File "/opt/conda/lib/python3.10/_weakrefset.py", line 51, in __init__
5879.1s	381	    self.update(data)
5879.1s	382	  File "/opt/conda/lib/python3.10/_weakrefset.py", line 124, in update
5879.1s	383	    for element in other:
5879.1s	384	  File "/opt/conda/lib/python3.10/_weakrefset.py", line 65, in __iter__
5879.1s	385	    for itemref in self.data:
5879.1s	386	RuntimeError: Set changed size during iteration
```

tqdm==4.66.1
Notebook

Spawn about 66 separate progress bars, the error seem to happen randomly.
